### ISSUE TITLE
Make Wiki searchable with Algolia 

### ISSUE THREAD

**Issue by mmvvaa** [DecentralVan/dctrl-admin#17]
There is a lot of detailed information about the meat space in the [Decentral Wiki](https://github.com/DecentralVan/decentral/wiki), thanks mainly to @chiselinc. 

The wiki is ideal for maintaining the repo up to date, but currently there is no easy way for members, specially new ones, to access it, aside from going directly to it.  

Integrating [Algolia](https://www.algolia.com/) would allow members to find out details about the space.

**Comment by TRhode** [comment]
issue for decentralVan/decentral
