### ISSUE TITLE
Hardware: Connect Pi to Mag Lock controller. 

### ISSUE THREAD

**Issue by TRhode** [DecentralVan/dctrl-admin#44]

**Comment by TRhode** [comment]
The 3 volt trigger on the rasp pi can be connected to the Control- and Control+ on the mag lock power supply - this allows a rasp pi to be installed beside the current installation. Next step is to run a network wire & five volt power / up to the door.

**Comment by dctrlcommons** [comment]
Now need to set up (2) new rasp pi's and sd cards with arch Linux and then configure for network, ssh, install node, and get the dctrl-fobtap repo running again.

**Comment by dctrlcommons** [comment]
First installation from: https://archlinuxarm.org/platforms/armv6/raspberry-pi : these instructions is booting into rootfs (similar to safe mode)
